name: previewapps-prod

on:
  push:
     branches: [development]
  pull_request:
     branches: [development]


jobs:

   build: 
     name: Build Docker image and deploy appication to EKS
     runs-on: ubuntu-latest

     steps:
     - name: git checkout 
       uses: actions/checkout@v2


     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build, tag, and push docker image to Amazon ECR
       env:
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         REPOSITORY: previewapps-prod
         IMAGE_TAG: ${{ github.sha }}
       run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  
   Deploy:
     name: Deploy appication to EKS
     runs-on: ubuntu-latest
     needs: build

     steps:  
     - name: git checkout 
       uses: actions/checkout@v2

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

     - name: Deploy application to EKS
       uses: docker://public.ecr.aws/z2u3g7p8/devops/actions-eks-deployer:v1
       env:
         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
         
       run: |
          sed -i -e "s/PROD-IMAGE-VERSION/${{ github.sha }}/g" ./kubeconfigs/values.yaml
          helm upgrade previewapps-prod-helm --install --wait ./kubeconfigs/ -f ./kubeconfigs/values.yaml --namespace previewapps-prod
          kubectl get pods -n previewapps-prod